apiVersion: v1
kind: Service
metadata:
  name: rental-car-service
spec:
  type: NodePort
  selector:
    app: rental-car
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 30011
